# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: airflow_connection
      conn_type: postgres
      conn_host: localhost
      conn_schema: airflow
      conn_login: postgres
      conn_password: 1452
      conn_port: 5433
      conn_extra:
  pools:
    - pool_name: airflow_pool
      pool_slot: 5
      pool_description:
  variables:
    - variable_name: airflow_variable
      variable_value: airflow_value
